language: node_js
node_js:
  - "8"

# install: npm install

#script:
#  - npm run test

#cache:
#  directories:
#  - node_modules

jobs:
  include:
    - stage: generator
      install: npm install
      script:
        - npm run test
      cache:
        directories:
        - node_modules
    - stage: acs
      script: cd app/templates/adf-cli-acs-template && npm install && npm test
    - stage: aps
      script: cd app/templates/adf-cli-aps-template && npm install && npm test
    - stage: acs-aps
      script: cd app/adf-cli-acs-aps-template && npm install && npm test
